swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /posts:
    get:
      operationId: "posts.read"
      tags:
        - "Posts"
      summary: "The posts data structure supported by the server application"
      description: "Read the list of posts"
      responses:
        200:
          description: "Successful read posts list operation"
          schema:
            type: "array"
            items:
              properties:
                user_id:
                  type: "integer"
                  example: 3
                username:
                  type: "string"
                  example: "bob"
                category:
                  type: "string"
                  example: "NCAA Football"
                title:
                  type: "string"
                  example: "Who will win? Ducks or Beavers?"
                url:
                  type: "string"
                  example: "http://www.example.com"
                body:
                  type: "string"
                  example: "Who do you think will win this year?"
                timestamp:
                  type: "string"
                  example: "2019-11-27 20:10:09"